_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 16
                - 23
                - 55
                - 61
            "4": 3.11.9
            "5": 0.18.1
            "6": 4.44.2
            "8":
                - 3
                - 5
            "12": 0.18.1
            "13": windows-amd64
batch_size:
    value: 1
epochs:
    value: 3
gradient_accumulation_steps:
    value: 8
learning_rate:
    value: 5e-05
max_length:
    value: 512
